// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvCk28ZwehXXqdLYbfXG-WG1bywy710EI',
    appId: '1:338592292074:web:0798d01147e9bc6505cb93',
    messagingSenderId: '338592292074',
    projectId: 'smart-meter-5cd74',
    authDomain: 'smart-meter-5cd74.firebaseapp.com',
    storageBucket: 'smart-meter-5cd74.firebasestorage.app',
    measurementId: 'G-8W3H9BXR0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX9tpZM-7nszCcZTCDqvWZeBRWJ6Ciesk',
    appId: '1:338592292074:android:5a4baab8e5e6e18305cb93',
    messagingSenderId: '338592292074',
    projectId: 'smart-meter-5cd74',
    storageBucket: 'smart-meter-5cd74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcjJSzgHBwIug1l7mHhEVaRp_CQi_APkY',
    appId: '1:338592292074:ios:d934f8c0f710eaf505cb93',
    messagingSenderId: '338592292074',
    projectId: 'smart-meter-5cd74',
    storageBucket: 'smart-meter-5cd74.firebasestorage.app',
    iosBundleId: 'com.example.smartmeter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcjJSzgHBwIug1l7mHhEVaRp_CQi_APkY',
    appId: '1:338592292074:ios:d934f8c0f710eaf505cb93',
    messagingSenderId: '338592292074',
    projectId: 'smart-meter-5cd74',
    storageBucket: 'smart-meter-5cd74.firebasestorage.app',
    iosBundleId: 'com.example.smartmeter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvCk28ZwehXXqdLYbfXG-WG1bywy710EI',
    appId: '1:338592292074:web:3a080a23a1eaca4f05cb93',
    messagingSenderId: '338592292074',
    projectId: 'smart-meter-5cd74',
    authDomain: 'smart-meter-5cd74.firebaseapp.com',
    storageBucket: 'smart-meter-5cd74.firebasestorage.app',
    measurementId: 'G-9E8VXTJEE8',
  );
}
